{"name": "Verify Connection List Page in Project", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=107.0.5304.107)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x01201ED3+2236115]\n\tOrdinal0 [0x011992F1+1807089]\n\tOrdinal0 [0x010A66FD+812797]\n\tOrdinal0 [0x0108DFFA+712698]\n\tOrdinal0 [0x010F506B+1134699]\n\tOrdinal0 [0x0110514A+1200458]\n\tOrdinal0 [0x010F18A6+1120422]\n\tOrdinal0 [0x010CA73D+960317]\n\tOrdinal0 [0x010CB71F+964383]\n\tGetHandleVerifier [0x014AE7E2+2743074]\n\tGetHandleVerifier [0x014A08D4+2685972]\n\tGetHandleVerifier [0x01292BAA+532202]\n\tGetHandleVerifier [0x01291990+527568]\n\tOrdinal0 [0x011A080C+1837068]\n\tOrdinal0 [0x011A4CD8+1854680]\n\tOrdinal0 [0x011A4DC5+1854917]\n\tOrdinal0 [0x011AED64+1895780]\n\tBaseThreadInitThunk [0x76686939+25]\n\tRtlGetFullPathName_UEx [0x773B8FD2+1218]\n\tRtlGetFullPathName_UEx [0x773B8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\labelpage.py\", line 20, in Project_xpath\n    context.driver.find_element(By.XPATH, btn_project_xpath).click()\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I launch chrome browser", "status": "passed", "start": 1668668648179, "stop": 1668668651457}, {"name": "When I open PushPullTouch homepage", "status": "passed", "start": 1668668651457, "stop": 1668668652650}, {"name": "And Enter username \"OCUA4\" and password \"1234\"", "status": "passed", "start": 1668668652650, "stop": 1668668652783}, {"name": "And click on Sign In button", "status": "passed", "start": 1668668652783, "stop": 1668668654071}, {"name": "Then navigate to Project Page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=107.0.5304.107)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x01201ED3+2236115]\n\tOrdinal0 [0x011992F1+1807089]\n\tOrdinal0 [0x010A66FD+812797]\n\tOrdinal0 [0x0108DFFA+712698]\n\tOrdinal0 [0x010F506B+1134699]\n\tOrdinal0 [0x0110514A+1200458]\n\tOrdinal0 [0x010F18A6+1120422]\n\tOrdinal0 [0x010CA73D+960317]\n\tOrdinal0 [0x010CB71F+964383]\n\tGetHandleVerifier [0x014AE7E2+2743074]\n\tGetHandleVerifier [0x014A08D4+2685972]\n\tGetHandleVerifier [0x01292BAA+532202]\n\tGetHandleVerifier [0x01291990+527568]\n\tOrdinal0 [0x011A080C+1837068]\n\tOrdinal0 [0x011A4CD8+1854680]\n\tOrdinal0 [0x011A4DC5+1854917]\n\tOrdinal0 [0x011AED64+1895780]\n\tBaseThreadInitThunk [0x76686939+25]\n\tRtlGetFullPathName_UEx [0x773B8FD2+1218]\n\tRtlGetFullPathName_UEx [0x773B8F9D+1165]\n\n", "trace": "  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\labelpage.py\", line 20, in Project_xpath\n    context.driver.find_element(By.XPATH, btn_project_xpath).click()\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 861, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\KnoDTec\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1668668654072, "stop": 1668668656085}, {"name": "Then navigate to Variant page", "status": "skipped", "start": 1668668658157, "stop": 1668668658157}, {"name": "Then navigate to connection list page", "status": "skipped", "start": 1668668658157, "stop": 1668668658157}, {"name": "Then Connection list Page should load successfully", "status": "skipped", "start": 1668668658157, "stop": 1668668658157}], "start": 1668668648179, "stop": 1668668658157, "uuid": "3c254e73-7e3b-4838-b967-57f23816f39d", "historyId": "33e2cd6641ab31cc167520654262e662", "fullName": "Push Pull Touch Connection List Page: Verify Connection List Page in Project", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Push Pull Touch Connection List Page"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}